name: Test - Windows

on:
  push:
    branches: [test-setup-node]
  pull_request:
    branches: [test-setup-node]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-unbound autotools

      - run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v2

      - name: Build
        run: ./autogen.sh && ./configure --with-network=regtest && make

      - name: Unit Tests
        run: ./test_hnsd

      - name: Setup Integration
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: Integration Tests
        working-directory: ./integration
        run:  |
              npm install
              npm run test
